//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLogixNET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlLogixNET.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The abbreviated type does not match the data type of the data object..
        /// </summary>
        internal static string AbbreviatedTypeError {
            get {
                return ResourceManager.GetString("AbbreviatedTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to access beyond the end of the object..
        /// </summary>
        internal static string AccessBeyondObject {
            get {
                return ResourceManager.GetString("AccessBeyondObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified array length does not match the destination array length..
        /// </summary>
        internal static string ArrayLengthException {
            get {
                return ResourceManager.GetString("ArrayLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to process one of the attributes..
        /// </summary>
        internal static string AttributeError {
            get {
                return ResourceManager.GetString("AttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beginning offset was beyond the end of the template..
        /// </summary>
        internal static string BeginOffsetError {
            get {
                return ResourceManager.GetString("BeginOffsetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device does not support CIP.
        /// </summary>
        internal static string CIPNotSupported {
            get {
                return ResourceManager.GetString("CIPNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimensions have not been set for this tag. You must set the dimensions before using the multi-dimensional index by using the SetMultipleDimensions function on the tag..
        /// </summary>
        internal static string DimensionsNotSet {
            get {
                return ResourceManager.GetString("DimensionsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified group already exists on the processor..
        /// </summary>
        internal static string GroupExists {
            get {
                return ResourceManager.GetString("GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified group was not found on the processor..
        /// </summary>
        internal static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a &quot;LogixTag&quot;..
        /// </summary>
        internal static string IncorrectArgTagType {
            get {
                return ResourceManager.GetString("IncorrectArgTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An insufficient number of attributes were provided compared to the attribute count..
        /// </summary>
        internal static string InsufficientAttributes {
            get {
                return ResourceManager.GetString("InsufficientAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IOI word length did not match the amount of IOI which was processed..
        /// </summary>
        internal static string InvalidIOILength {
            get {
                return ResourceManager.GetString("InvalidIOILength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processor did not return enough data to complete the data structure..
        /// </summary>
        internal static string InvalidResponseSize {
            get {
                return ResourceManager.GetString("InvalidResponseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item referenced could not be found on the processor..
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IOI path could not be deciphered by the processor or the matching tag does not exist..
        /// </summary>
        internal static string MalformedIOI {
            get {
                return ResourceManager.GetString("MalformedIOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough data was sent to the processor to execute the command..
        /// </summary>
        internal static string NotEnoughData {
            get {
                return ResourceManager.GetString("NotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not establish connection with the processor..
        /// </summary>
        internal static string ProcessorNotConnected {
            get {
                return ResourceManager.GetString("ProcessorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session could not be established..
        /// </summary>
        internal static string SessionNotEstablished {
            get {
                return ResourceManager.GetString("SessionNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session could not be registered with the processor..
        /// </summary>
        internal static string SessionNotRegistered {
            get {
                return ResourceManager.GetString("SessionNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session connected and registered..
        /// </summary>
        internal static string SessionRegistered {
            get {
                return ResourceManager.GetString("SessionRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A socket error has occurred. Check the error code for the socket exception number..
        /// </summary>
        internal static string SocketError {
            get {
                return ResourceManager.GetString("SocketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag could not be found on the processor..
        /// </summary>
        internal static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed in object could not be converted to the required type..
        /// </summary>
        internal static string TypeConversionError {
            get {
                return ResourceManager.GetString("TypeConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type returned by the processor does not match the tag type. The processor returned a .
        /// </summary>
        internal static string TypeMismatch {
            get {
                return ResourceManager.GetString("TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified field of the UDT does not exist in this structure..
        /// </summary>
        internal static string UDTMemberNotFound {
            get {
                return ResourceManager.GetString("UDTMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
